apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aap-medlem-request.v1
  namespace: aap
  labels:
    team: aap
spec:
  pool: {{kafka-pool}}
  acl:
    - team: medlemskap
      application: medlemskap-oppslag
      access: read
    - team: aap
      application: medlem
      access: write
